package io.github.anitvam.agents.bdi.events

import io.github.anitvam.agents.bdi.intentions.IntentionID
import io.github.anitvam.agents.bdi.events.impl.EventImpl

/**
 * A BDI Agent can react to two types of Events: External and Internal.
 * An Event is a pair where the [Trigger] represents the change that took place and the [IntentionID] is the
 * associated intention.
 *
 * As External Events are not generated by intentions, they are represented by having an empty [IntentionID]
 */
interface Event {
    /** Denotes the change that took place for the Event generation */
    val trigger: Trigger

    /** The Event's associated Intention. Its value is null if the Event is an External one. */
    val intention: IntentionID?

    /** @return true if this is an Internal Event, otherwise false. */
    fun isInternal(): Boolean = intention == null

    /** @return true if this is an External Event, otherwise false. */
    fun isExternal(): Boolean = intention != null

    companion object {
        fun of(trigger: Trigger, intention: IntentionID? = null) = EventImpl(trigger, intention)
    }
}
