[versions]
coroutines = "1.10.2"
dokka = "2.2.0"
kermit = "2.0.4"
kotlin = "2.4.10"
alchemist = "43.1.5"
tuprolog = "1.3.0"


[libraries]
kermit = {module = "co.touchlab:kermit", version.ref = "kermit"}
alchemist-api = { module = "it.unibo.alchemist:alchemist-api", version.ref = "alchemist" }
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}
kotlinx-coroutines-test = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref="coroutines"}
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
caffeine = "com.github.ben-manes.caffeine:caffeine:3.2.3"

tuprolog-core = { module = "it.unibo.tuprolog:core", version.ref = "tuprolog" }
tuprolog-solve-classic = { module = "it.unibo.tuprolog:solve-classic", version.ref = "tuprolog" }
tuprolog-parser-core = { module = "it.unibo.tuprolog:parser-core", version.ref = "tuprolog" }
tuprolog-dsl-core = { module = "it.unibo.tuprolog:dsl-core", version.ref = "tuprolog" }
tuprolog-dsl-unify = { module = "it.unibo.tuprolog:dsl-unify", version.ref = "tuprolog" }
tuprolog-dsl-theory = { module = "it.unibo.tuprolog:dsl-theory", version.ref = "tuprolog" }
tuprolog-serialize-core = { module = "it.unibo.tuprolog:serialize-core", version.ref = "tuprolog" }


tuprolog-unify = { module = "it.unibo.tuprolog:unify", version.ref = "tuprolog" }

tuprolog-full = { module = "it.unibo.tuprolog:2p", version.ref = "tuprolog" }
tuprolog-ide = { module = "it.unibo.tuprolog:ide", version.ref = "tuprolog" }
tuprolog-repl = { module = "it.unibo.tuprolog:repl-jvm", version.ref = "tuprolog" }
tuprolog-theory = { module = "it.unibo.tuprolog:theory-jvm", version.ref = "tuprolog" }
tuprolog-parser-theory = { module = "it.unibo.tuprolog:parser-theory-jvm", version.ref = "tuprolog" }
tuprolog-dsl-solve = { module = "it.unibo.tuprolog:dsl-solve-jvm", version.ref = "tuprolog" }
tuprolog-oop-lib = { module = "it.unibo.tuprolog:oop-lib-jvm", version.ref = "tuprolog" }

[bundles]
alchemist-api = [
    "alchemist",
    "alchemist-api"
]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "7.0.23" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "1.9.0" }
kover = "org.jetbrains.kotlinx.kover:0.9.8"
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "4.5.6" }
npm-publish = "org.danilopianini.npm.publish:4.1.5"
publishOnCentral =  { id = "org.danilopianini.publish-on-central", version = "9.2.10"}
taskTree = { id = "com.dorongold.task-tree", version = "4.0.2" }

