package it.unibo.jakta.agent

import it.unibo.jakta.event.Event
import it.unibo.jakta.event.EventInbox
import it.unibo.jakta.event.EventStream

/**
 * The view on an [Agent] from the [AgentLifecycle] perspective.
 */
interface RunnableAgent<Belief: Any, Goal: Any, Skills: Any> {

    /**
     * [Event] stream emitted by the agent.
     * Includes both [Event.Internal] either generated by the [MutableAgentState] or received from the [internalInbox]
     * and [Event.External] generated from the [it.unibo.jakta.environment.Environment]
     */
    val events : EventStream<Event>

    /**
     * An inbox of [Event.Internal] that the [AgentLifecycle] can use
     * to send events that allows the agent to advance.
     */
    val internalInbox: EventInbox<Event.Internal>

    /**
     * The mutable state of the agent.
     */
    val state: MutableAgentState<Belief, Goal, Skills>
}
