import it.unibo.tuprolog.core.Atom

val blockA = Atom.of("A")
val blockB = Atom.of("B")
val blockC = Atom.of("C")
val blockD = Atom.of("D")
val blockE = Atom.of("E")
val blockF = Atom.of("F")
val blockG = Atom.of("G")
val blockH = Atom.of("H")
val blockI = Atom.of("I")
val blockJ = Atom.of("J")
val blockK = Atom.of("K")
val blockL = Atom.of("L")
val blockM = Atom.of("M")
val blockN = Atom.of("N")
val table = Atom.of("table")
