import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docSidebar: [
    { type: 'doc', id: 'intro' },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'tutorials/index' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'How-To',
      link: { type: 'generated-index', title: 'How-To' },
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'generated-index', title: 'Reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Explanation',
      link: { type: 'generated-index', title: 'Explanation' },
      items: [
        {
          type: 'category',
          label: 'The BDI model',
          items: [
            { type: 'doc', id: 'explanation/basic-concepts/bdi' },
            { type: 'doc', id: 'explanation/basic-concepts/beliefs' },
            { type: 'doc', id: 'explanation/basic-concepts/goals' },
            { type: 'doc', id: 'explanation/basic-concepts/plans' },
          ],
        },
        {
          type: 'category',
          label: 'Nodes and Environment',
          link: { type: 'doc', id: 'explanation/nodes' },
          items: [
            { type: 'doc', id: 'explanation/nodes' },
            { type: 'doc', id: 'explanation/basic-concepts/skills', label: 'Skills' },
          ],
        },
        {
          type: 'category',
          label: 'Jakta Incarnations',
          items: [
            { type: 'doc', id: 'explanation/incarnations/index', label: 'Overview' },
            {
              type: 'category',
              label: 'Prolog Incarnation',
              items: [{ type: 'autogenerated', dirName: 'explanation/incarnations/prolog' }],
            },
            { type: 'doc', id: 'explanation/incarnations/string' },
          ],
        },
        { type: 'doc', id: 'explanation/incarnations/alchemist' },
        { type: 'doc', id: 'explanation/communication' },
        { type: 'doc', id: 'explanation/execution-model' },
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'generated-index', title: 'API' },
      items: [
        // Generated by Dokka at deploy time (see .github/workflows/deploy-website.yml)
        { type: 'link', label: 'All modules (latest)', href: 'pathname:///api/index.html' },
        { type: 'link', label: 'jakta-api', href: 'pathname:///api/jakta-api/index.html' },
        { type: 'link', label: 'jakta-dsl', href: 'pathname:///api/jakta-dsl/index.html' },
        { type: 'link', label: 'jakta-core', href: 'pathname:///api/jakta-core/index.html' },
        { type: 'link', label: 'alchemist-jakta-incarnation', href: 'pathname:///api/alchemist-jakta-incarnation/index.html' },
        { type: 'link', label: 'jakta-string-incarnation', href: 'pathname:///api/jakta-string-incarnation/index.html' },
        { type: 'link', label: 'jakta-prolog-incarnation', href: 'pathname:///api/jakta-prolog-incarnation/index.html' },
        { type: 'link', label: 'Older versions (javadoc.io)', href: 'https://javadoc.io/doc/it.unibo.jakta' },
      ],
    },
    {
      type: 'category',
      label: 'Showcase',
      items: [{ type: 'autogenerated', dirName: 'showcase' }],
    },
    {
      type: 'category',
      label: 'History',
      link: { type: 'generated-index', title: 'History' },
      items: [{ type: 'autogenerated', dirName: 'history' }],
    },
  ],
};

export default sidebars;
