import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docSidebar: [{type: 'autogenerated', dirName: '.'}],


  // But you can create a sidebar manually
  
  docSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: "Explanation",
      items: [
        { 
          type: 'category', 
          label: 'Basic Concepts',
          items: [{ type: 'autogenerated', dirName: 'basic-concepts' }],
        },
        { type: 'autogenerated', dirName: 'explanation' },
      ],
    },
    {
      type: 'category',
      label: "How-To",
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
  ],
   
};

export default sidebars;
