name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: DanySK/build-check-deploy-gradle-action@4.0.43
        with:
          should-deploy: ${{ runner.os == 'macOS' && steps.detect-secrets.outputs.has-secrets == 'true' }} # Deploy from macOS since it supports all the platforms
          deploy-command: |
            ./gradlew publishAllPublicationsToProjectLocalRepository zipMavenCentralPortalPublication releaseMavenCentralPortalPublication
          should-run-codecov: ${{ runner.os == 'Linux' }}
          codecov-directory: build/reports/kover
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  release:
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release
    needs:
      - build
    runs-on: ubuntu-latest
    if: >-
      !github.event.repository.fork
      && github.ref == 'refs/heads/main'
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:
      - name: Fetch sources
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: package.json
      - uses: DanySK/build-check-deploy-gradle-action@4.0.43
        env:
          STAGING_REPO_ID: ${{ needs.staging-repo.outputs.staging-repo-id }}
          ORG_GRADLE_PROJECT_releaseStage: true
        with:
          retries-on-failure: 1 # Fail fast during release
          build-command: true
          check-command: true
          deploy-command: |
            npm install
            npx semantic-release
          should-run-codecov: false
          should-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}

  success:
    runs-on: ubuntu-latest
    needs:
      - release
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
